Create app
safar1212/dogfacts pull request #1
Opened 2022-07-29 13:36 UTC by safar1212

In this pull request, I completed the React capstone project.

Below is the link to the loom video.

[loom video](https://www.loom.com/share/3c901a18c08a4cfe9c1c4225176282b8)

2022-07-29 18:01 UTC, codepantha requested changes
# STATUS: REQUIRED CHANGES ♻️ 

## Hi @safar1212 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ No linter errors
✔️ App working well


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 18:01 UTC, codepantha commented on README.md
> +<!-- [Live Demo Link](https://stupendous-dieffenbachia-47916f.netlify.app/) -->
- [ ] You have built a good project and a professional README, but to make it even better, kindly add a link to the deployed project so everyone can access it 👍

2022-07-29 18:01 UTC, codepantha commented on README.md
> +<!-- ![2022-07-16_17-47-56](https://user-images.githubusercontent.com/78845635/179355540-641c6e4d-3c01-4e3c-9e00-89e22f0b4d7f.jpg) -->
- [ ] I think it would be better to add screenshots of your project here otherwise you can take out this section entirely. I strongly suggest you add the screenshots 👍

2022-07-29 18:01 UTC, codepantha commented on src/tests/HomePage.test.js
> +    expect(DetailsPage).toMatchSnapshot();
- [ ] You have taken some snapshots 👏 However, I will suggest that you write some integration tests using React Testing Library

2022-07-29 18:01 UTC, codepantha commented on src/Components/HomePage.js
> +        </div>
- [ ] As per requirements, you need to use a Filter stateless component to filter data retrieved from the API. Kindly extract this into a `Filter` component where you can perform the filter operation 👍 At the moment, you can only sort, but you also need to filter when a user searches by e.g dog name

2022-07-29 18:01 UTC, codepantha commented on src/Components/HomePage.js
> +        </div>
- [ ] Kindly follow the design guidelines when styling the individual cards. Notice the borders and the arrows at the top right of each card 🙏 
### Design guideline
![image](https://user-images.githubusercontent.com/46839548/181818060-97a4fbbd-d0fd-46c4-94f0-3a7d61ff7c28.png)
### Your Design
![image](https://user-images.githubusercontent.com/46839548/181818123-bf912a98-15ad-46d6-bf17-08a4ce6a0640.png)

2022-07-29 18:08 UTC, safar1212 commented on src/tests/HomePage.test.js
> +    expect(DetailsPage).toMatchSnapshot();
@codepantha , Can you please explain the integration test? Others have also implemented the same things, and their projects are excepted. I have submitted two types of tests. 
Looking forward to hearing from you!

2022-07-29 18:58 UTC, codepantha commented on src/tests/HomePage.test.js
> +    expect(DetailsPage).toMatchSnapshot();
The purpose of integration testing is to confirm that different components of the application interact with each other. For instance, what do you expect to see when the `Homepage` renders correctly? Or when you click a dog item from the list on your `Homepage` it renders the `Details` page of that particular dog. Now, what do you expect to see on that Detail page?

2022-07-30 08:06 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @safar1212 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 08:06 UTC, tresorsawasawa commented on README.md
> +
- [ ] Good job making some of the changes required by the previous review. So, I noticed that the link you added is broken,  make sure you correct it to make the documentation professional.

2022-07-30 08:06 UTC, tresorsawasawa commented on src/Components/HomePage.js
> +
- [ **OPTIONAL** ] **RECOMMENDED:** Kindly make sure you remove all the commented code lines to make your code base cleaner and for [best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

2022-07-30 08:06 UTC, tresorsawasawa commented on src/Components/HomePage.js
> +  // };
- [ **OPTIONAL** ] **RECOMMENDED:**  As I mentioned in the previous comment,  make sure you remove all the commented code lines to make your code base cleaner and for [best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

2022-07-30 08:06 UTC, tresorsawasawa commented on src/Components/navbar.js
> +  const links = [
- [ **OPTIONAL** ] **RECOMMENDED:** Kindly make sure you rename the `navbar.js` file to `Navbar.js` as it is a component it has to be capitalized. Right now, it blocks to create the **production**(`npm run build`) that can help for deployment.

2022-07-30 08:06 UTC, tresorsawasawa commented on src/Components/HomePage.js
> +    </div>
- [ ] As mentioned by the previous reviewer, Kindly make sure you follow the design guidelines when styling individual cards. Notice the borders and the arrows at the top right of each card prayer. Right now, you can't differentiate the limit of each card. I know you can do it :muscle: :muscle:   

| Template Design | Your current Design |
| ----------------------- | ------------------ |
| ![Template_design](https://user-images.githubusercontent.com/46839548/181818060-97a4fbbd-d0fd-46c4-94f0-3a7d61ff7c28.png) |![Screenshot from 2022-07-30 09-24-30](https://user-images.githubusercontent.com/83042742/181880231-56a27bec-89d1-44f9-baa7-1f434f71d0d7.png) |

2022-07-30 08:06 UTC, tresorsawasawa commented on src/tests/HomePage.test.js
> +    expect(DetailsPage).toMatchSnapshot();
- [ ] As mentioned by the previous reviewer, kindly make sure your App has some integration tests using React Testing Library (If you want you can perform a mocking data fetching and Redux Store connection). You can take a look at these [articles](https://medium.com/expedia-group-tech/integration-testing-in-react-21f92a55a894) or [this](https://blog.logrocket.com/testing-react-apps-jest-react-testing-library/) to have an idea.

2022-07-30 08:06 UTC, tresorsawasawa commented on src/Components/Filter.js
> +};
- [ ] Good job trying to implement the changes required by the previous reviewer. But as he mentions ad as required for the project you are supposed to implement a feature that filters data retrieved from the API.  Right now, you can only sort. (e.g.: I can suggest you implement a search_bar with a feature where the user can type the **dog-name** to get it from the list).

2022-07-30 17:17 UTC, Gambit142 requested changes
Hi @safar1212 👋, 

Great work on making the changes requested by a previous reviewer 👏 

 ## Highlights
- Al linters checks passed 💯 
- Implemented Filter function 💯 
- Adjusted design to suit guidelines 💯 

However, you've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

- Kindly consider the optional suggestion I made in the comments under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 17:17 UTC, Gambit142 commented on README.md
> +
- [ ] Great job attempting to deploy the page. However, I noticed that the link is broken. It shows a 404 page. It would be nice to deploy the project properly because that would most likely be the first thing that recruiters will check when they visit your repository. Below is an image of what I see when I click the link you attached to the README.md file

![image](https://user-images.githubusercontent.com/77106962/181933399-72d08b42-2bc0-41ac-8f79-981f7850d6d7.png)

2022-07-30 17:17 UTC, Gambit142 commented on src/App.js
> +import NavBar from './Components/Navbar';
- [ ] When I start your application, I get this error which is shown in the image below:

![image](https://user-images.githubusercontent.com/77106962/181933924-31d81c19-6c09-46d5-b5f3-ddd45677a8bd.png)

The other reviewer suggested that you rename the file that has the `NavBar` component from `navbar.js` to `Navbar.js.` Kindly make the change and this error will disappear. 👍

2022-07-30 17:17 UTC, Gambit142 commented on src/Redux/mainPage.js
> +
- [ ] Kindly remove all unused or unnecessary codes from your file. It helps keep the codebase clean. 👍

2022-07-30 17:17 UTC, Gambit142 commented on src/tests/HomePage.test.js
> +
- [ ] Kindly remove all unused or unnecessary codes from your file. It helps keep the codebase clean. 👍

2022-07-30 17:17 UTC, Gambit142 commented on src/tests/HomePage.test.js
> +});
- [ ] [Optional] It would be nice to write tests for the `Details` component to make sure that the component renders the right data. 👍

2022-07-30 17:24 UTC, safar1212 commented on src/App.js
> +import NavBar from './Components/Navbar';
@Gambit142 what are you talking about. the file is already named. Navbar.js

2022-07-30 17:32 UTC, safar1212 commented on src/App.js
> +import NavBar from './Components/Navbar';
![2022-07-30_22-32-06](https://user-images.githubusercontent.com/78845635/181935010-b9b577e3-60bf-4dab-851b-4fae3680c4eb.jpg)

2022-07-30 18:03 UTC, uwadonat approved these changes
## Hi @safar1212,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# Highlights
- Professional readme file ✔️
- Good communication with reviewers ✔️
![approval](https://user-images.githubusercontent.com/65860678/181935953-6d46cd20-1d70-44e5-8baa-df03df3b4528.gif)


# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-30 18:05 UTC, merged

2022-08-01 07:22 UTC, Gambit142 commented on src/App.js
> +import NavBar from './Components/Navbar';
@safar1212, kindly check the error message in the image I attached.